version: 1.0.{build}

image:
  - Visual Studio 2019

configuration:
  - Debug
  - Release

before_build:
  cmd: |-
    git submodule update --init --recursive
    mkdir build
    cd build
    cmake --version
    cmake ..
    cmake -G .

build:
  verbosity: normal
  parallel: true

